#----------------------------------------------------------------------
# This file was generated by C:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

background = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAAA3NCSVQICAjb4U/gAAAAnUlE"
    "QVR4nO3XsQ3DIABFwThKz/5bwgRkAaooRfxyV2KaJxfoX3POx8kY43i+1rr1/efxNExwneA6"
    "wXXX3vv44dfez2/d/7s/LLhOcJ3gutdd3k97+EOC6wTXCa6zh+sE1wmuE1xnD9cJrhNcJ7jO"
    "Hq4TXCe4TnCdPVwnuE5wneA6e7hOcJ3gOsF19nCd4DrBdYLr7OE6wXWC6wTXvQEuf6SwjP0+"
    "WAAAAABJRU5ErkJggg==")
getbackgroundData = background.GetData
getbackgroundImage = background.GetImage
getbackgroundBitmap = background.GetBitmap

#----------------------------------------------------------------------
background2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAIAAAD9MqGbAAAAA3NCSVQICAjb4U/gAAAAnElE"
    "QVQ4je2RsQ7DIAxE7XM+gf//QSQGVsDuYMmJaJ1IXbr0JoN53Bm41kqJSilZi4hw07vXn/wB"
    "CcDMYum1qsbOkZFrrdaaqjKzkwBiSUR8vXgje+9zThHxMw7H+dRTRMYYDpgZM3vUk8w8PZWI"
    "OOPOzBxpj6je5dnMTFU3wwdPf5Lw35R6xjcAEJEPZBbVxwOwhTxnychHfU++ACWXaKxnr0d5"
    "AAAAAElFTkSuQmCC")
getbackground2Data = background2.GetData
getbackground2Image = background2.GetImage
getbackground2Bitmap = background2.GetBitmap

#----------------------------------------------------------------------
open_folder = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAVdJ"
    "REFUOI3Fkz1uGzEQhT/KLnSINA7gLpWOoAurS3IQF9oIUpBCgKoFyd2Vhj9DphDMtaL8FC5C"
    "YAASw/fmzRvSmMUD71mLd6GBR4Afh2+12x3uks8fP/D0/Mn8k6DbHVitViyXSwBEhGEY6LqO"
    "77uX+jcSYxYPfP3yuf6aKKVQSmn7Wms713q97py7KiilsF6vbwhSSuScSSm1iDESQkBECCGw"
    "3+9nAoCcMwAxRlSVWusduO97RITtdjt7oKqtcoyxSRYRSil3YO890zQhIrcEMUaMMZRSGngc"
    "xyY754z3nhACOefZA1Ul54wxhpRS6/E1RAQR4Xw+N7Cq4py7PqScczPsVe7vwM45jDGEEG4J"
    "VBVVvav+FiwiGGO4XC7NJ+/93EIIgePxyOl0YhzHm5HFGJsHqkopBVVlmqZ5jJvNhmEYsNZi"
    "raXve6y1eO8RkT8+ZfPff+NPkkJ83wX9NIcAAAAASUVORK5CYII=")
getopen_folderData = open_folder.GetData
getopen_folderImage = open_folder.GetImage
getopen_folderBitmap = open_folder.GetBitmap

#----------------------------------------------------------------------
close_folder = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAZ9J"
    "REFUOI3Fk8uuEkEQhr+5EBI2hEDYsBk1PAXPoe7UtfoSel5FDTv1RSAhGVg5kpAhBJIJzLVn"
    "6IsLM31EF2dxFlbSm67+v79SVe04rsdjwn2UGnD2+70Jw/CfxHQ65cnTZ85DAD8MQ4IgYDQa"
    "AaC1RmvNYrHgZ/TDPATxjTEMBoMbsVKKyWTCer3m+7evRkpJe5RSvHr9xkJ9pRRKKRzHsYA0"
    "TS3k71itVrcVKKW4Xq+4rovWms1mY6tp4a2zUoput8uXz59Ma+ZrrZFS4vs+cRyjlCIIAlz3"
    "dkDGGAuTUhJFEUKI+wo8z+N8PtPr9WiahqZprFhKae/quuZwOBBFER8+3jkWcLlcMMYwHo/J"
    "8xyANtcKhRAIIVgul8xms989aOlJktDv96nrGmOMFbbiqqoQQhDHMafTiecvXjoArlKKsiwB"
    "GA6H9mFZluR5TpqmpGlKlmUcj0d2u511t1NI05ROp8N8Pr9pWtvpP/cjSRLevnt/vwdaa7bb"
    "LXVd43keRVGQ5zlZlpFlGUVRUBQFVVVR1zWOc7uYzn//jb8AgT9W1KzFnk8AAAAASUVORK5C"
    "YII=")
getclose_folderData = close_folder.GetData
getclose_folderImage = close_folder.GetImage
getclose_folderBitmap = close_folder.GetBitmap

#----------------------------------------------------------------------
save = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAiFJ"
    "REFUOI2lk79rU1EUxz/35eU1SdM0iJiA1kozpC4KgvoHdHCwuji4aDeFgpv4B4iggyDo5OQq"
    "OunQDuKm2apzOjSYaAq22JT39P289x6H0rShLQ5+t3vO/f64h3uUcnL8D9Ty8rJUKhV83z/y"
    "UrlcRmtNHMdcnb+m9vfcYrHI1NQUxWLxn25ra2sHai5ArVbD8zystYcSRYTBYEC/3z8oYK1F"
    "RGi1WiONmZkZOp3O8NxoNA41cLXWiAizs7MEQUAcx0xOTg5F9qc4DK6IICK02+1hsVqt8uT9"
    "FhNjEKaaY2WP/kaEchrcf/lFrCgGfsS96429JzSbTaIoQmuNMYYojJm71OTKuTIfV37w4ObZ"
    "Eee3nzd58a6DsxtvdXWVXq/H+vo6xhjCJGMr0AB8WPk5Qk4NbG6nKGX3EkxPTxOGIcYYtNY4"
    "jiInkFOWZ4sXcJQggLVCyYUkSfB/pzszsNbS7XaHDvV6nULeIU4yHr35Rk5BZizWWGR3oAIl"
    "z+JmWTYk7Ye2QmI0rpMHBIVBKYVYQcSidUaaaNwoigAIgmBEIAgz8splcX4CbVPAAQFRloLr"
    "8fR1j1/+n52fuLS0tOesNaVSCWPq5MhjiXj19S7HS6dROGyG37lz8TkOBcIkxb11e2FkOXZx"
    "4+EnOVOHWjlg7vxlqt5JcGA7PsWJcc24B65SqKPWeeFxS2KdUR2rUnAraJuhrEWJwaqQdrfD"
    "hp/xFwuUHO1AngzoAAAAAElFTkSuQmCC")
getsaveData = save.GetData
getsaveImage = save.GetImage
getsaveBitmap = save.GetBitmap

#----------------------------------------------------------------------
saveas = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAq9J"
    "REFUOI2lk11oU3cYh5//yelpThqTCGsTpm3a+pFOmTLHJgwdiF4oyLxwl1a88Qu89lovFKog"
    "m6CTicquCrsYnbNxKkVFAwpWLU6aftiaSIy2prSJbU5OTv6vF2qvOnex9/p94Pe+PD+lDB//"
    "Z1QymZRQKESxWPzP5Xgkj2/8Or7gGmbf3KJ+2Y+Ytm3T3NyMbdufhGdf/ol/agT7y07CbV8x"
    "PZ7g9b1uTIBoNIplWWitF4TvX++io6VCcMUGpp4NYimXRaEYz+sWY2qtERFSqdSCcH64h83f"
    "+om0b6OS78YKKDKPB1HlGdYd6FGm53mICB0dHZRKJRzHIRwOA3D7ygm2fmcTXr4dJ/cLhuVR"
    "F4zjK4+SOHBDARgigoiQTqfJ5XIUCgWUUjzqO8emdfWEl+/AyZ3FqKviFlvJ3+rnnHSxpysl"
    "DwZfyfwJiUSCcrkMQHbgD9qjZZpW/4D76jw+S3Bm4kzc7Se44xLHmj7n97uTnO4ZwwAQEYaG"
    "hshms1y+cIRFksPIjJN/chqNw+zUEp73PaBtbxIAtwaT0y5KaYyPCeLxOI2NjUQbMqzasB+A"
    "4Z4Uj69Nkb45wOpD1wBoisYImJpKpULxrYspImityWQyAIyMTuA+vULb2u+ZmSzwYmCMfzZe"
    "Jdk9hq5p5ENiBAKWxqxWqwDEYjEAnoxM8NOvZ/j6i3ZCy9bwtP03FKCooZRCtCCi8bwqbsXD"
    "/Pi4UqkEwOFTfwNw7K85toRWcnCjjaddwAABURq/aXGyO0uhOPvexN7e3nlxPM8jEAhQq8Xw"
    "UYemzMWH+/gs0ILCYHLuBXu/+RkDP3MVF3NX5261kIE7j96R1hhEgyU2r11PxFoCBkw7S2lq"
    "8GiwwFQK9W913n08JY5XJVIfwW+G8HQVpTVKamg1RzozxkSxyjuuEjvJ/Zcm2gAAAABJRU5E"
    "rkJggg==")
getsaveasData = saveas.GetData
getsaveasImage = saveas.GetImage
getsaveasBitmap = saveas.GetBitmap

#----------------------------------------------------------------------
delete = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAaVJ"
    "REFUOI2lk09rE0EYh5/Zzf5Jdhd6SNGvUPDYVgt6F49GaCNiEEXB9FOJ30JFqQfBgNWkVHtv"
    "q2azu9ZWkw0z+3qRxHTTg+Q9zry/h3mfmVHKslmkrIXS5wEH7W358rQtFzX3mndlr9Wa2Z8A"
    "DtrbguOC6/H58ZMSpLfZFLtWxVlaorfZlBJAtEaMRnkeuB77rQcyDW+JFVSxawH5t++M02QC"
    "Vv9K3H/4SJTjYgUh5uwUc3qCaINdC6iEAXm/zzhNWX35Qs0FAOzduy+W52JHERQFFAJiyPsx"
    "4zRj9dU0XJIIcOX5M6VPfoI2cPwVjo/AFIyTpBQGqJxf+GsECgNagxRgDEqVsvNP0G3cEdvz"
    "wWhYrkO9DkbjhCGd6zdKtzPjoNtoiO1XqQQB+SAmzzJEa9wworpcZzQYMIpjrnY6ZYnd2w2x"
    "fZ9KUCOPE/IfGWtvXiuAd2vr4kURweVLDOOYYT9m49NHNTOCFAWIkPcHjLJ0EgbY6LxXw2TA"
    "r8NDLGWhrKmPmRE+3Lwl+vcZ6zs7c429XVkRx/e5trt78Tv431r4N/4B+HWxfQZGrocAAAAA"
    "SUVORK5CYII=")
getdeleteData = delete.GetData
getdeleteImage = delete.GetImage
getdeleteBitmap = delete.GetBitmap

#----------------------------------------------------------------------
start = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAARhJ"
    "REFUOI3F07tKA0EUgOF/NqzRwsKACiqIIKIWwfhkqV1L8SWUgFgJqewVRAjEInYWCxYWahRy"
    "0VwmM7Mz6wNkNgZTePr/O6c5QgQ5ZplgpjoLOKm+pdcPrfTPgLGC+vOIau3zV8QLqCShtJkn"
    "bhoqN+8TES8wUAkmTdkohDy9Kk6rL5mIF+jLFKUdnYFhe3WO+ENRrsRexAt8Sc1IO9o9Q7Or"
    "2VvLEzcVpXJ9DPEC3aFBaktfWYbKIrVjJC07ywvTXfDdS5Da4lxKGApuH9usz8NVVBRTAW1p"
    "kMqSDwV3jQ5biwGX0cFYnAnIfoI0jvtGh92lHBdRyRtnAk4aao0W+4WA8yP/5snAIKG4EnJ2"
    "fDgxBhD//o0/uyOBAnyP4hIAAAAASUVORK5CYII=")
getstartData = start.GetData
getstartImage = start.GetImage
getstartBitmap = start.GetBitmap

#----------------------------------------------------------------------
designer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAgJJ"
    "REFUOI3Fk09IlGEQh59PP3VPQVAJmUX2x0pDygULKfFcJ0HoJAZ18NDRLnkJrE5BRAlChw6B"
    "BMWCgWGUB7NY0TBYNtZozTU3tW1dNZP1e993psOCERFBHhoYGAZ+P2aGZzyvqJjNRNGm1Jsx"
    "iL64p5n5MfX/Rfykr1urj1RTmunFS0yldSIxh6iAKCKCU0GcK9QiiAgqQs2BCtZS/Zw41UTJ"
    "l15e9z+EvoFxFXV/zMCKruadZldFr3df0cXPw+oSbRrpCunVjkb1VQSAkehbnHMYYwmMIQgM"
    "xgSsB0K2uJ6VvE/V0VaCmVs8HXxEPFvN2Yt38J0WDMQJ1jmstVhjMNZgAsvkUhUdreUsLHss"
    "ftvG7VedxGPKhfZWwuGw54srGJxuPL5xJCNgLGRylsmBeTIrHtH3kPhk+fp9F7HVk5RXHATA"
    "d84CEHv3AWstxjqCwLJnXy13I2lamiuJTQvPRxdYzi0wnxyldm8ZDfWHPYAiJw6AyexOhj7u"
    "58FIiJraOp6N5WhpriSe9hmMpplNvmEmPsSh3SG6Opo2pvWdLayQWiwllUqRnJ6jf7iMvscv"
    "WVrKYaWYfH6drVtKCDFLpOeyF+n5yYQv4jAO6suTHNsBGt6O6Bqd7fWIKk48REEEbtyc+A0q"
    "v6GuirZL15iaTv2VwPPnzjA+eP+Xnvffv/EH0qExgf8XR24AAAAASUVORK5CYII=")
getdesignerData = designer.GetData
getdesignerImage = designer.GetImage
getdesignerBitmap = designer.GetBitmap

#----------------------------------------------------------------------
user_component = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmdJ"
    "REFUOI19k0tIlFEUx3/nm88pQRpqJNAihTC0EB80YqLRIIErN7kWW7bQwrZt2okLN4XIiESJ"
    "BhIViDQoYSJmPsjJB7RpmMAHmG8/dJxv7ndb6IwjWv/V4d5zfvzvOfeIGC4Avs3N6k3L4n+6"
    "lZvLtaxsST0zE8HGzg53fT5iSmErhe04KK3RWgMQCoWYD4f5vbykc7KvJCFGInC0xnEc0l0u"
    "LrjdxKJR1MEBTizG7u4ulmVRU17O3BHkNMBxcAGRSIS21lbMeBzDtnkbCGBvb1NRVsbLnh7C"
    "4TAfh4Y4E7CztcXrri7uVVfj8XjweDxU+f30dXcT29vD7/dTW1tLTk7OaYByHKanpii4eZPi"
    "khIMEQwRCouKuJGfz/zMDCKSzD3TwW2fjy/Dw0yMj2MYBoYI0xMTjI6MUFxaimkYiAjOmQCl"
    "yPR6edLcTKCjg421NTbW1+kKBHjU1ITX68VtmrhEcJQ6nqMYLsRw0RsMalspHY3H9Vlasyy9"
    "sr2tV/f3dW8wqBN1ZqoDEUG05iAe55yZvEIpxeTCJz7PDLCzt4Eds3kTfKHraxrFTE0SwBDh"
    "+IWHGpjsI7Q0iL/Sx9VLeQwvfKB/vp22vmfaOAEQSUJS9X6sm+L8YpShKMq6jxKbO4UVvBt9"
    "xUnAUbEAccchdtSstc0V0iSD2oJGAJ5Wd3L9chG2HTsGRKPRw6YezT/VSebFLBaWx2gZagCg"
    "ZbCBX6s/SEtzHwOslE0UkeQ/UFpTllfF+OxX3Jj0z7XjFpPR0Ah1VQ+RxDp39vboyOIi/9If"
    "vvNzeZL9qEX6+QweVNbzuO65/AX8qjPFFhKlrAAAAABJRU5ErkJggg==")
getuser_componentData = user_component.GetData
getuser_componentImage = user_component.GetImage
getuser_componentBitmap = user_component.GetBitmap

#----------------------------------------------------------------------
python = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAfVJ"
    "REFUOI19kzFrk1EUhp9zv6QGJCWDgn4W+w2KgyKItBQEKbGBQgtWOjgJgu7iD9B/0E2c3KSU"
    "gh0KbaHUoUgpLoWQxkVIwcHgFDHNkDS95zg0uUlI9UyHe8997vuec6+IiwD4eliy340G/4vb"
    "ScL1q7H0r6W6Sa1e5+HEBCfe0/aetireDDMDoFgsUj464kf1p43H1wLEdRM1Q1XZPzhgfWuL"
    "k2aT7e1tyuUyx8fHNBoNZqemOOxAhhSoKgJUq1WezM7S9p6Z6Wk+7+6SJAm1Wo13y8sAVCqV"
    "YQuqipMzZU6EdBT1ipwjn89jZmSzWYrFYtgLFrwqy+vrPJ2bw4kEyHyhwJe9PVLOIZ0LvOow"
    "QFV5trDA6uZmADgRNnZ2mC8UGEmlAkT7AD0L3g9YyGYyoejK6Ci/6nUAIhHU+2EFp94jQBzH"
    "rGxsAPBhbY04jgFIRxGZdJp0FHHaBxhQICLMTE6G2b9cXATg1c6ncODRzTsDCgLAdxQ4EXoO"
    "e/Hi3gPGL+Z4u7fJfX/hHwARxCz0oj/el/YBKCS3qH875x0MKDDjVBU1YySK+NNu8fruNDdy"
    "l1AzVkvfh5vYbDYBkM74ujCAVquFmeGcw4mE2gEFjb6f2IWYGd6Mj4+fY5z9lyiVGqgNgMu5"
    "HG+Wls5p33AkY2Mh/wsHdN7bZa6XmQAAAABJRU5ErkJggg==")
getpythonData = python.GetData
getpythonImage = python.GetImage
getpythonBitmap = python.GetBitmap

#----------------------------------------------------------------------
cog = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAACdklE"
    "QVQokVWSwUrrQBSGz6STmlZjh2pWppFWEVy4yiYLkUYEl/oQPoX4DoJP4Au40Y26EXFhN4WU"
    "ggsXLTRgWxporc00mcnM3EUuF++3PgfO958fKaXgF0qpKIomkwkAmKZZq9Xgf7R8SErJGOOc"
    "I4S+vr7W1tYIIUEQSCmVUpTSLMsAQAiBAUBKOR6PR6MRAOzv7y+XS0IIpXRlZUVK+fDwkCRJ"
    "vV73PK9QKKAsy6IoopSur69Pp9PZbDabzWzb5pwPBgPGmG3b29vb7XabEOJ5Hi4UCkKI0WjE"
    "GGOMEUIqlUqWZQihRqMhhOCc93q9t7c33/cRQiiX7vf7SZIwxuI4juM4DENd1xuNBkJICDGf"
    "z03TPDo6UkqhIAgYY8vlcmtrK7+t1+s1m02lVLvddhwnSZKNjY3X11dd1zHG2mKxqNfrlmVN"
    "JpNSqTQcDn3f39nZ2d3dPTw8DMPQMIzhcOi67unpaafT0YQQaZoyxpRSSqnV1dVisfg7+CzL"
    "pJSc8ziOKaV4sVjc399blrW3tzefz23bDoIgF3t/f7csi3Ouadrd3Z0Qolqt/pX++PiIoghj"
    "jBDKf5emaa1Wk1J+f38nSWKa5snJCcZYA4DPz89Op2NZlpRS07RyuZxnbxiGruumaTqO8/T0"
    "9Pj4CAAYAH5+fjY3N8vlcrfbDcMwTdNmsymlvL29LZVKruseHBxUKpU0TQFAU0q5rkspvb6+"
    "brVaFxcXhmEYhoExLhaLV1dXLy8vl5eXhJDz83MAwAghADg7O/M8r1qt5g7T6ZRSmvfl5uZm"
    "PB47jpPXFEkp851/tFqt5+dnzrnv+8fHx0ophFCuBwB/AFfsdPF/219HAAAAAElFTkSuQmCC")
getcogData = cog.GetData
getcogImage = cog.GetImage
getcogBitmap = cog.GetBitmap

#----------------------------------------------------------------------
shield = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhpJ"
    "REFUOI11k01PE1EUhp/7MdOPqWAp2BZTogsTNijuNSwMKhATFyb+BhPjjzEm/gYTQjBiFdRF"
    "Iwt2RtcspKEthYIlkZnJTDvXRWUmhPYmJ+fc3PM+uV+vEFIxanyobhqAJ8uPxKgeMQpQ/fzF"
    "5MdzAPw5/cvy48WhEAmwUd0yte0dE4s3v5pM2ma6XKJcKuJkUnz8tBWv17Z3zEZ1MNcAnucy"
    "VRhnde29AXDSNtenSxwfHwMwXS7SbB2wurZuMCBNiOe5xACAqckCY1dyGGPwfZ92ux1v0/M8"
    "nGyG/NVxjDEopWm1OwlACMHZmUunczTqrgiCIK6zjoOUMgEopQiCgDAM46YwDHFdD9/36fX6"
    "RFGElBKlNIVCAaVUArAsmzN3cKZer0e328V1fYQQCCERYiCUclC7nkc2N5YAHCdHo1En52To"
    "dE4wBpSyEELGovOstaZ72mWyWE6eMT8xget5BEEfITRa22htY1nnORWHbaeJIkM+P5EA5udm"
    "RdiLUEoPFVlWCq1TWFYaYyQGw/zcrIgBAJXKDI1mi2zWuSTSOvU/bJqtOpXKzMWfCLCytCj6"
    "UZ/9xj526qJIaxulNHv1XfpRyMpS8q0veeH1m7fm6PCQUrHCzRu3EELye2+XZqvO1LVJXr18"
    "ccETQ830bnXd/Pr5g0K+hBDQOTng9p27PH/29JKhRrpx61vNbH+vAXDv/gIPHywMdeM/UIHB"
    "8cMB93MAAAAASUVORK5CYII=")
getshieldData = shield.GetData
getshieldImage = shield.GetImage
getshieldBitmap = shield.GetBitmap

#----------------------------------------------------------------------
page_white_stack = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAB3UlE"
    "QVQokT2SPW9qMQyGY8dJClXVpUIgJEBHjJVAYmuH/nA2FphaGDoxlYEeJsRQCse1fQdfkclK"
    "/PHm8Qu73a6uazMLIQAAADRN0+/3B4OBmSHi7SmEoKq03+9nsxkiMnOMUURijKvVKoTQ7XZL"
    "KbdsZk4pERGpKjP7qKZp2u22iMzn8263+/z8PBwOQwhmllIyM7perznn8/l8PB5fX19FJOcc"
    "QvB4tVqJyHA4REQXTKUUVUVEEQkhiMh2u93tdmbWarVyzovF4vHxcTqdjkYjACBVVVUXZ2al"
    "lO/v77e3NzMjIhGZzWZEtFwuVXU8HtPf3x8AxBibpkFEVc05+8Dz+ayqIvLw8DCZTDabDRGh"
    "f4WZW62Wmbk8J5hS8oIQwv39/cvLS13XyMz+ITPzUc4kxggAKaVSyul0OhwOnkApJd/O5XIB"
    "AGZWVSJy8IhIRDnn6/Xqo4iZmfnW++7uzsv8xuMQgsdEhP1+f71ef3x8bLdbM/v9/fUHAHCp"
    "/7dL5K6hwWDQ6/WcoGMVEWfta8k5u84YIxHhjUan01mv1+/v75+fn947xuigb74QEXLkAFBV"
    "VVVVl8vFmd5S3XOI+PPzU0oBd68ft+rX19d+vyciZs45e4KIlFKenp7+AR9qU0taMoZHAAAA"
    "AElFTkSuQmCC")
getpage_white_stackData = page_white_stack.GetData
getpage_white_stackImage = page_white_stack.GetImage
getpage_white_stackBitmap = page_white_stack.GetBitmap

#----------------------------------------------------------------------
copy = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAbVJ"
    "REFUOI19k01rE1EUhp9z7k2DCVSoIwzVhYuuFAvdFOzKnf4Ef5V/QveCbl0JXXXrxmAyJmBJ"
    "0xBoSNomuR8u0txMJsGzm5nD8z7v3BkRNVTn558iTmazrfsAL7KM/Ekmq2u7a2l8e8vx0REz"
    "55iHwMJ7Qox0u106V1f0h9cxz54KgO4ChBCIIRCcI8znzO/vmU6nTCYTzl6+kt/9PpfXg5gM"
    "qsqdfh+xFuc9hwcHNOp1AEajEZ++fY1FUdDudNYVqsqHeZ6U/w6HPMsyGvU6b05PmTlHs9mk"
    "KApShf8pv319LL3BgOndHY9qNerWoqo459YAHwIighFhz9q0uFK+7PX4cXGRntVU8d6vKwTv"
    "URFUFUJgzy4Pp6z8q91OAcaYTYBzDgWMCFQgAKpKDCEFGJFUwQJ475GSQRWiqgTvU4A+hG4A"
    "VAQtGZQhxhhCyUBFWJQBzjlkVWEZuQExIgTvscYQVUGV8XhcAYgsT2JdPEEU+H5+TqvVSu/l"
    "eZ6vAQvnEHeDmn0CbEFUhLOTEz68e59+otUsv8QHHfFj1D4mxogAIcYt5Z2A/UaDj5+/7Fyo"
    "KlfnHzlxBEtlsoe+AAAAAElFTkSuQmCC")
getcopyData = copy.GetData
getcopyImage = copy.GetImage
getcopyBitmap = copy.GetBitmap

#----------------------------------------------------------------------
insert_before = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAARlJ"
    "REFUOI21UrtKBEEQrNm7U0xETDUwEPyBzc3VH/AHjAQfd4ehKMbG9w8+EIxUxA9Y10cqJsKZ"
    "qAhqMDM9y5bRLLOuqOdpw9Dd0F1V3T1KRTX0Y1GYdE4f6MSyF4B6mIgjtg4fcdt95eT4sGo1"
    "V+mcg4jAOVd6O7t7qgSwedBlvaYw1FDonD3j5u6F62sLEBGICIwx8GBZlhWkKtzBxv49n94s"
    "FqdHMTUxonoewThie34MjYHBHzWXFJwcH326PJKFJ4k8zwEAM7Nz5R0AQBzHpWLfEHqSSNO0"
    "OgJJJElSYQobvxzht1YoaLea9Er8ra21sNbCGAOtNbTWRXx5da3+VsHK8hL9p/GsH5nP04vK"
    "eftWEH1f8s8A73ITzc9oAppbAAAAAElFTkSuQmCC")
getinsert_beforeData = insert_before.GetData
getinsert_beforeImage = insert_before.GetImage
getinsert_beforeBitmap = insert_before.GetBitmap

#----------------------------------------------------------------------
insert_after = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAASVJ"
    "REFUOI2tU7lKBEEQfT2zq5iImGpgIPgDk5urP+APGAkeu2IoirGxfoMHgpEa7AeM45GKibBG"
    "HqAGfTLPaNrpnQHFsaCooqlX9V5XtxBRjCYWNUIDaBXJRrdDACAJay2stdBaQ2sNpRSklJBS"
    "+vzm9k4AgGgqwTNYW12hMQbGGD91cPJVdi0GG/wfg8uLc9YVkPSRJPI8BwDMzS+IoAEAJEkS"
    "FBeAciSJLMuqDEgiTdPKpDKw1kQUez/ovdI5x/LZTx5IMJbYPXvGQ/+D05OjottZp7UWxhj/"
    "Ngo/PDoO72DntM9WLDDSFtjvveH+8Z1bm0soVquUQtHMOfetoLzG7ZMnvnxqLM+OY2ZqrLLz"
    "OgskKEvsLU6gPTT8K3CFwV+s8W/8Atqrzipx4I88AAAAAElFTkSuQmCC")
getinsert_afterData = insert_after.GetData
getinsert_afterImage = insert_after.GetImage
getinsert_afterBitmap = insert_after.GetBitmap

#----------------------------------------------------------------------
element = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALxJ"
    "REFUOI1jZGRiZqAEMFGke1AYwIIuMH33vf97rnzBqcFFh4ch01WJEacBuy5+ZBDi4mRgZoKo"
    "+ffvP8O//6jyeF3w989vhv//2Bj+/EOI/Wf4z8DIwMjw999/hr9/fqOoxwiDv39+M/z58wtF"
    "jJEB4hpmJkbCBvz584uBhYUNXRhFHq8Bv3/9xKkZmzymAT9/4DcATR7DgO9fP+E1gOHPNxQu"
    "RiwkB9swTFm8A6f+nFgPhsMTEXzGoZ+ZADTmRMu9KsXLAAAAAElFTkSuQmCC")
getelementData = element.GetData
getelementImage = element.GetImage
getelementBitmap = element.GetBitmap

#----------------------------------------------------------------------
interface = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAXxJ"
    "REFUOI2lkr1LXFEQxX/z3nPfrsIaLRYkBP+ExGYhdgGDXyyKXQorkz8lXbqUsU8hLoR8NAls"
    "E1IEQa3FQlREwTW7Uffj3TuTYtGXZJdl0YFpzr33zLlnjkgQcp8KBrlUrtRs7fWZlSs1uyNB"
    "ndW5EcqV+t0ULD6Nefv+iNnpqPtQgnCg/rR1ZL3wgRT0K+m3hW87x9Zouy48l4mYefJQbgnK"
    "lZp9/tFicTpm5dmoAHzdPrSJsRyFB1lE08cWwNmvJicXDZ5PPZIIOi6/XBpn/UOVjz8PDOCy"
    "6SjksyTuv80pFPJZ9k5+AxBB6vLyTJ5ScUIANr7vm1Ml8YYAzoPzHjVjOBPhvKYEL+YLArD5"
    "Jh3kVXEKzbanlSiqqRK1BK8dgqDzhe6kOa9ctxIum47EK97sts3kXwW9PDivN3AKSI/1CDhv"
    "qYK/k1YqTkqpOClxKJxWr8gNBcRRSO6mhwJOq1fEYYe5bw7efdm12nW7Cx8dzvBq4XGag/vU"
    "HxTitbs4HzLgAAAAAElFTkSuQmCC")
getinterfaceData = interface.GetData
getinterfaceImage = interface.GetImage
getinterfaceBitmap = interface.GetBitmap

