#----------------------------------------------------------------------
# This file was generated by F:\Python25\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

open_group = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAALhJ"
    "REFUOI3dkzEKwkAQRf+s9iqorcpWOUYgkCJVbrGHUK+UKkUgkE49hKvrAYJ6gR07QWGySrBx"
    "2pn/Zj6fIVID9CnVS/1TwGG/4/vtyiHAUGpYa+Gcw8WdebFc0dcXAECSJGiaBid7FC/pBBAR"
    "sixDVVXijGjhuUEp5HmOtm3ZGIPpbP5iJ5iC9x5FUWC92dK7OAhgZpRliTRNxZlOC3VdI45j"
    "dKUgArTWiKIIo/FEFAMA/fEvfFoPsYsxj6F/1isAAAAASUVORK5CYII=")
getopen_groupData = open_group.GetData
getopen_groupImage = open_group.GetImage
getopen_groupBitmap = open_group.GetBitmap

#----------------------------------------------------------------------
close_group = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGZJ"
    "REFUOI1jZGRiZqAEMFGkewQZsHvXzv/tba3/sUoyMjHjxXv27Pmvpqb2X01N7T82ebwu2L1r"
    "5/+srCwGY2Nj0r1AjGacBhCrGacBZ86cYWBgYGA4e/YsHCclJWE1gHE0KVNuAAC3GSYVpU9A"
    "5QAAAABJRU5ErkJggg==")
getclose_groupData = close_group.GetData
getclose_groupImage = close_group.GetImage
getclose_groupBitmap = close_group.GetBitmap

#----------------------------------------------------------------------
open_group2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAQBJ"
    "REFUOI1jZGRiZqAEMFGkmyYGvP7++//zr7/+k23Aj7//Gfqf/mU48uYnUYZgGPDrHwPD0hd/"
    "GTJu/2ZY8uQHQUMwDPjzD6KnSY6ZoePRH4alBAzBMOAvlJZjZ2RolGdmaH/8h+HYW9zewYwF"
    "JKVKHIwMbQosDKFXfzOc/4A9YDEMYGKE0MyMDAwPfjIwVD/4w7BGm5XBUICNkSgDmKHKHv9k"
    "YKh9+IehSo6FwVKYHatmBgYGBgZGJmYU/Ojr3/8yR77/1zvx/f/K57//o8ujYxZ0A9mZGRii"
    "JZgZgkWYGMyF8NgMcwB6Zvrw4/f/v/8ZGIQ5WQlqxmoAqYDizAQAJQpTXW+NGlkAAAAASUVO"
    "RK5CYII=")
getopen_group2Data = open_group2.GetData
getopen_group2Image = open_group2.GetImage
getopen_group2Bitmap = open_group2.GetBitmap

#----------------------------------------------------------------------
close_group2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGZJ"
    "REFUOI1jZGRiZqAEMFGkewQZsPbZ9/8JV779xybHQkjzskff/ufd+UueC5Y8+va/9ME/hjRp"
    "3PbglFlGhGacBqx99v1/3p2/BDXjNGDzO0h4zXr6By7mKsTEsACLWsbRpEy5AQD2GCW6X2Cx"
    "UAAAAABJRU5ErkJggg==")
getclose_group2Data = close_group2.GetData
getclose_group2Image = close_group2.GetImage
getclose_group2Bitmap = close_group2.GetBitmap

